### PR TITLE
Add Douyu and Youtube links in educational tab

### PR DESCRIPTION
**Pull request by RaphaelMeudec**
I added the Douyu links to each element + added small youtube/douyu links in each card that opens the link in a new tab. Here is a screenshot of it. Let me know if there are some adjustments to make!

image

### CODE REVIEW

**Comment by rgbayrak** [comment]
Looks great, thank you @RaphaelMeudec!

**Comment by rgbayrak** [comment]
Uff the logos appear very large unlike the photo above 😅 

Minor edits perhaps that can go along with this. 
- If there is a logo, title dont need a link? 
- Center align text in cards
- shrink logo size :D 

@RaphaelMeudec 🙏🏼

**Comment by RaphaelMeudec** [comment]
Which browser are you using? I don't have issues on the live website with the logo site on my side?

**Comment by rgbayrak** [comment]
Oh, it is self fixed! (google chrome)

**Comment by RaphaelMeudec** [comment]
Maybe you had poor internet connection and the css did not properly load. I'll add the other points to the next PR!

**Pull request merged**
