### PR TITLE
I think I should be there :)

### PR DESCRIPTION
**Pull request by vborghe**
but can't upload my pic, you can use the same you have [here](https://ossig.netlify.app/) - thanks!

### CODE REVIEW

**Comment by rgbayrak** [comment]
Please:
- upload your image to https://github.com/ohbm/osr2022/tree/main/img/team  (labeled your name_surname.jpg not jpeg)
- fix the text added where it says stephanie_noble to your name_surname (matching the img)

**Comment by rgbayrak** [comment]
you should be able to PR

**Comment by vborghe** [comment]
should be OK

**Comment by rgbayrak** [comment]
Looks great, merging!

**Pull request merged**
