### PR TITLE
Speaker view in Panel page

### PR DESCRIPTION
**Pull request by RaphaelMeudec**
This is ongoing work to add speakers info in the panel page. Let me know if you have some feedback on it? @rgbayrak  @vborghe

Things I need to fix (add others if you have):

- still some missing images/affiliations for some speakers
- some images are not round, need to fix the ratio

Here is the preview:

image

### CODE REVIEW

**Comment by rgbayrak** [comment]
We probably would prefer it to be clickable. There will be links to the speaker bio and pages. Static image is ok but not we want. 

Roza

**Comment by rgbayrak** [comment]
@RaphaelMeudec Looks good so far. In addition to the things you listed below, 

- we would like to highlight the roles in the panel, whether it is co-moderator or speaker, below the speaker photo as in here: https://ohbm.github.io/osr2022/volunteers/ Name, role (co-moderator or speaker), affiliation, link to pages. 
- If something is missing, it should not break the page instead, it just does not show. 
- Perhaps 3 people per row would make it look more tidy?

**Comment by RaphaelMeudec** [comment]
@vborghe @rgbayrak PR is ready for review, I added the twitter/github extra links, added the panel role and filled the missing affiliations. Here is an updated version of the visual:

image

**Comment by vborghe** [comment]
LGTM - thanks a lot, @RaphaelMeudec

**Comment by RaphaelMeudec** [comment]
Indeed, it closes #14, sorry for not adding it in the description (again)!

**Pull request merged**
